name: Mintlify automerge
on:
  push:
    branches:
      - main
    paths:
      - 'essentials/**'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge main -> mintlify
        uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          from_branch: main
          target_branch: mintlify
          github_token: ${{ secrets.EMILY_PAT }}
