name: Mintlify automerge
on:
  push:
    branches:
      - main
    paths:
      - 'essentials/**'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Merge main -> mintlify
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout mintlify
          git merge --ff-only main
          git push origin mintlify
        with:
          type: now
          from_branch: main
          target_branch: mintlify
          github_token: ${{ secrets.EMILY_PAT }}
