name: Production automerge with same branch

on:
  push:
    branches:
      - production

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.EMILY_PAT }}
          base: main
          title: 'Sync production into main'
          body: 'Automated PR to sync production into main'
          labels: automated,sync
          branch: sync-production-to-main
          commit-message: 'Sync production into main'
          delete-branch: true
