name: Production automerge with same branch

on:
  push:
    branches:
      - production

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.EMILY_PAT }}" | gh auth login --with-token

      - name: Create PR from production to main
        run: |
          gh pr create \
            --base main \
            --head production \
            --title "Sync production into main" \
            --body "Automated PR to sync production into main" \
            --label "automated,sync" || echo "PR already exists or no changes"
