name: Production automerge with new branch

on:
  push:
    branches:
      - production

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create production -> main pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.EMILY_PAT }}
          commit-message: 'chore: sync production to main'
          title: 'Sync production to main'
          body: 'Automated PR to sync production branch to main branch'
          branch: sync-production-to-main-${{ github.sha }}
          base: main
          delete-branch: true
          labels: |
            automated
            sync
