name: Production automerge
on:
  push:
    branches:
      - production
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.EMILY_PAT }}
          commit-message: 'chore: sync production to main'
          title: 'chore: sync production to main'
          body: 'Automated PR to sync production branch to main'
          branch: sync-production-to-main
          base: main
          labels: |
            automated pr
            sync
